
from specialproducts.models import SpecialProductsWidget
from profileactions.models import ProfileActionsWidget
from quickcart.models import QuickCartWidget
from productcatalog.models import ProductCatalogWidget
from productlist.models import ProductListWidget
from productcatalog.models import ProductCatalogWidget
from storeactions.models import StoreActionsWidget
from storecontact.models import StoreContactWidget
#from storesearch.models import StoreSearchWidget
